########################################
# App
########################################
app.dynamodb.table-name=fatec-ai-bot-core

########################################
# OpenAPI / Swagger
########################################
quarkus.smallrye-openapi.info-title=FATEC AI BOT Backend API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.path=/openapi
%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.swagger-ui.path=/swagger

########################################
# DynamoDB - Local (dev) com LocalStack
########################################
%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

########################################
# DynamoDB - Producao (AWS real)
# Defina via variaveis de ambiente no deploy
########################################
%prod.quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
%prod.quarkus.dynamodb.aws.credentials.type=default
